from __future__ import annotations

from enum import Enum, IntEnum


STRATEGY_ID = "SCALP_PO3_REVERSAL"
ANALYSIS_SYMBOL = "NQ"
TRADE_SYMBOL = "MNQ"
MICRO_TRADE_SYMBOL = "MNQ"
CONFIRMATION_SYMBOL = "ES"

TICK_SIZE = 0.25

PRODUCTION_START_ET = "09:30"
PRIME_START_ET = "09:55"
PRIME_END_ET = "10:20"
SECONDARY_END_ET = "10:45"
EOD_FLATTEN_ET = "15:55"

DAILY_PIVOT_N = 5
DAILY_LOOKBACK = 20
H4_PIVOT_N = 3
H1_PIVOT_N = 3
M1_PIVOT_N = 2

MIN_NQ_SWEEP_TICKS = 6
MIN_ES_SWEEP_TICKS = 3
MIN_SMT_STRENGTH = 0.15
PREFERRED_SMT_STRENGTH = 0.25
SMT_MAX_LAG_BARS = 3

MIN_BODY_PERCENT = 0.50
STRONG_BODY_PERCENT = 0.60
REJECT_BELOW_BODY_PERCENT = 0.35

MIN_RR_A = 1.5
MIN_RR_B = 2.0
SCORE_THRESHOLD_A_PLUS = 6.0
SCORE_THRESHOLD_A = 5.0
SCORE_THRESHOLD_B = 5.5

A_PLUS_RISK_PCT = 0.005
A_RISK_PCT = 0.0035
B_RISK_PCT = 0.002
MAX_DAILY_LOSS_PCT = 0.01
MAX_WEEKLY_LOSS_PCT = 0.03
MAX_TRADES_PER_DAY = 2
MAX_FULL_LOSSES_PER_DAY = 1

ENTRY_OFFSET_TICKS = 1
STOP_MIN_BUFFER_TICKS = 4
STOP_ATR_BUFFER_FRACTION = 0.05
BE_TRIGGER_R = 1.0
EARLY_BE_TRIGGER_R = 0.75
TIME_STOP_MINUTES = 20
TIME_STOP_MIN_R = 0.25


class Po3Phase(Enum):
    DISABLED = "DISABLED"
    PREMARKET_LOAD = "PREMARKET_LOAD"
    IDLE = "IDLE"
    BIAS_SET = "BIAS_SET"
    H4_PRIMED = "H4_PRIMED"
    LIQUIDITY_ARMED = "LIQUIDITY_ARMED"
    SMT_CONFIRMED = "SMT_CONFIRMED"
    IFVG_CONFIRMED = "IFVG_CONFIRMED"
    ORDER_WORKING = "ORDER_WORKING"
    IN_POSITION = "IN_POSITION"
    BREAK_EVEN_SET = "BREAK_EVEN_SET"
    DONE_FOR_DAY = "DONE_FOR_DAY"


class TradeDirection(IntEnum):
    SHORT = -1
    FLAT = 0
    LONG = 1


class SetupTier(Enum):
    A_PLUS = "A+"
    A = "A"
    B = "B"
    NONE = "NONE"


class EntryType(Enum):
    STOP_CONFIRMATION = "STOP_CONFIRMATION"
    IFVG_RETEST = "IFVG_RETEST"
