SPY:
  symbol: SPY
  sec_type: STK
  exchange: SMART
  currency: USD
  tick_size: 0.01
  tick_value: 0.01
  primary_exchange: ARCA

QQQ:
  symbol: QQQ
  sec_type: STK
  exchange: SMART
  currency: USD
  tick_size: 0.01
  tick_value: 0.01
  primary_exchange: NASDAQ

IWM:
  symbol: IWM
  sec_type: STK
  exchange: SMART
  currency: USD
  tick_size: 0.01
  tick_value: 0.01
  primary_exchange: ARCA
