SPY:
  root_symbol: SPY
  exchange: SMART
  primary_exchange: ARCA

QQQ:
  root_symbol: QQQ
  exchange: SMART
  primary_exchange: NASDAQ

IWM:
  root_symbol: IWM
  exchange: SMART
  primary_exchange: ARCA
