from __future__ import annotations

from enum import Enum, IntEnum


STRATEGY_ID = "SCALP_IVB_AUCTION"
ANALYSIS_SYMBOL = "NQ"
TRADE_SYMBOL = "MNQ"
MICRO_TRADE_SYMBOL = "MNQ"
TICK_SIZE = 0.25

A1_ENABLED = True
A2_ENABLED = True
A3_ENABLED = False
A1_RISK_MULT = 1.0
A2_RISK_MULT = 0.5
A3_RISK_MULT = 0.25

IVB_START_ET = "09:30"
IVB_END_ET = "10:00"
NO_NEW_ENTRIES_AFTER_ET = "15:30"
NORMAL_FLATTEN_ET = "15:45"
HARD_FLATTEN_ET = "15:55"

MIN_BREAK_CONDITIONS = 3
MIN_BUFFER_PTS = 2.0
MIN_BUFFER_RANGE_FRACTION = 0.05
MIN_HOLD_SECONDS = 60
MAX_CHASE_EXTENSION_RANGE_FRACTION = 0.40

A1_MIN_SCORE = 65.0
A2_MIN_SCORE = 65.0
FULL_SIZE_SCORE = 85.0
THREE_QUARTER_SIZE_SCORE = 75.0
HALF_SIZE_SCORE = 65.0

TP1_QUANTILE = 0.65
TP2_QUANTILE = 0.90
MIN_R_TO_TP1 = 1.5
A2_MIN_R_TO_TP1 = 1.2
PREFERRED_R_TO_TP1 = 2.0
STOP_CAP_IVB_FRACTION = 0.35
TP1_EXIT_FRACTION = 0.70

BASE_RISK_PCT = 0.005
MIN_RISK_PCT = 0.0025
MAX_RISK_PCT = 0.0075
DAILY_SOFT_LOSS_PCT = 0.01
DAILY_HARD_LOSS_PCT = 0.015
MAX_TRADES_PER_DAY = 3
MAX_LOSSES_PER_DAY = 2
MAX_CONSECUTIVE_LOSSES = 2

MIN_IVB_RANGE_POINTS = 25.0
MAX_IVB_RANGE_POINTS = 180.0
ADAPTIVE_MIN_IVB_MULT = 0.40
ADAPTIVE_MAX_IVB_MULT = 2.50


class IvbAuctionPhase(Enum):
    S0_PRE_OPEN = "S0_PRE_OPEN"
    S1_IVB_FORMING = "S1_IVB_FORMING"
    S2_IVB_LOCKED = "S2_IVB_LOCKED"
    S3_AWAITING_BREAK = "S3_AWAITING_BREAK"
    S4_BREAK_CONFIRMED = "S4_BREAK_CONFIRMED"
    S5_ENTRY_HUNT = "S5_ENTRY_HUNT"
    S6_IN_TRADE = "S6_IN_TRADE"
    S7_FLAT_DONE = "S7_FLAT_DONE"
    S8_RECLAIM_WATCH = "S8_RECLAIM_WATCH"


class IvbModule(Enum):
    A1_CONTINUATION = "A1_CONTINUATION"
    A2_RECLAIM = "A2_RECLAIM"
    A3_MEAN_REVERSION = "A3_MEAN_REVERSION"


class TradeDirection(IntEnum):
    SHORT = -1
    FLAT = 0
    LONG = 1


class EntryTrigger(Enum):
    PROFILE_RELOAD = "PROFILE_RELOAD"
    ABSORPTION_RESPONSE = "ABSORPTION_RESPONSE"
    MOMENTUM_RESTART = "MOMENTUM_RESTART"
    RECLAIM_RETEST = "RECLAIM_RETEST"
    RECLAIM_BREAK = "RECLAIM_BREAK"
