from __future__ import annotations

from backtests.shared.auto.types import Experiment

BASE_MUTATIONS = {
    "flags.use_momentum_stall": True,
    "flags.use_drawdown_throttle": False,
    "flags.vol_50_80_sizing_mult": 0.85,
}

PHASE_FOCUS: dict[int, tuple[str, list[str]]] = {
    1: ("CONTEXTUAL CLASS T / ETH_PM", ["total_trades", "expectancy_dollar", "profit_factor"]),
    2: ("NORM-VOL M SHORT PRECISION", ["total_trades", "net_profit", "profit_factor"]),
    3: ("HIGH-VOL M LONG ADDITIVE", ["total_trades", "expectancy_dollar", "net_profit"]),
    4: ("CLASS F CONTEXTUAL QUALITY", ["total_trades", "profit_factor", "expectancy_dollar"]),
    5: ("FINAL CONTEXT STACK", ["total_trades", "net_profit", "profit_factor"]),
}

_TARGETED_PHASE_CANDIDATES: dict[int, list[Experiment]] = {
    1: [
        Experiment(
            "t_secondary_eth_pm_context",
            {
                "param_overrides.CLASS_T_SECONDARY_ENABLED": True,
                "param_overrides.CLASS_T_SECONDARY_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.CLASS_T_SECONDARY_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_T_SECONDARY_MIN_CONTEXT_SCORE": 4,
                "param_overrides.CLASS_T_SECONDARY_TREND_STRENGTH_MIN": 0.20,
                "param_overrides.CLASS_T_SECONDARY_PIVOT_RECENCY_H": 20,
                "param_overrides.CLASS_T_SECONDARY_COMPRESSION_MAX": 1.85,
                "param_overrides.CLASS_T_SECONDARY_MIN_HIST_RATIO": 0.60,
                "param_overrides.CLASS_T_SECONDARY_MAX_BREAKOUT_GAP_ATR": 0.55,
                "param_overrides.CLASS_T_SECONDARY_MAX_STOP_DIST_ATR": 2.45,
            },
        ),
        Experiment(
            "t_secondary_prime2_pm_context",
            {
                "param_overrides.CLASS_T_SECONDARY_ENABLED": True,
                "param_overrides.CLASS_T_SECONDARY_ALLOW_RTH_PRIME2": True,
                "param_overrides.CLASS_T_SECONDARY_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.CLASS_T_SECONDARY_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_T_SECONDARY_MIN_CONTEXT_SCORE": 3,
                "param_overrides.CLASS_T_SECONDARY_TREND_STRENGTH_MIN": 0.25,
                "param_overrides.CLASS_T_SECONDARY_PIVOT_RECENCY_H": 18,
                "param_overrides.CLASS_T_SECONDARY_COMPRESSION_MAX": 1.80,
                "param_overrides.CLASS_T_SECONDARY_MIN_HIST_RATIO": 0.65,
                "param_overrides.CLASS_T_SECONDARY_MAX_BREAKOUT_GAP_ATR": 0.60,
                "param_overrides.CLASS_T_SECONDARY_MAX_STOP_DIST_ATR": 2.50,
            },
        ),
        Experiment(
            "t_short_eth_pm_context",
            {
                "param_overrides.CLASS_T_SHORT_ENABLED": True,
                "param_overrides.CLASS_T_SHORT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.CLASS_T_SHORT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_T_SHORT_MIN_CONTEXT_SCORE": 4,
                "param_overrides.CLASS_T_SHORT_TREND_STRENGTH_MIN": 0.20,
                "param_overrides.CLASS_T_SHORT_PIVOT_RECENCY_H": 14,
                "param_overrides.CLASS_T_SHORT_COMPRESSION_MAX": 1.75,
                "param_overrides.CLASS_T_SHORT_MIN_HIST_RATIO": 0.70,
                "param_overrides.CLASS_T_SHORT_MAX_BREAKOUT_GAP_ATR": 0.55,
                "param_overrides.CLASS_T_SHORT_MAX_STOP_DIST_ATR": 2.20,
            },
        ),
        Experiment(
            "t_dual_pm_context_stack",
            {
                "param_overrides.CLASS_T_SECONDARY_ENABLED": True,
                "param_overrides.CLASS_T_SECONDARY_ALLOW_RTH_PRIME2": True,
                "param_overrides.CLASS_T_SECONDARY_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.CLASS_T_SECONDARY_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_T_SECONDARY_MIN_CONTEXT_SCORE": 3,
                "param_overrides.CLASS_T_SECONDARY_TREND_STRENGTH_MIN": 0.20,
                "param_overrides.CLASS_T_SHORT_ENABLED": True,
                "param_overrides.CLASS_T_SHORT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.CLASS_T_SHORT_ALLOW_RTH_PRIME2": True,
                "param_overrides.CLASS_T_SHORT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_T_SHORT_MIN_CONTEXT_SCORE": 3,
                "param_overrides.CLASS_T_SHORT_TREND_STRENGTH_MIN": 0.20,
            },
        ),
    ],
    2: [
        Experiment(
            "normvol_short_prime2_context",
            {
                "param_overrides.NORM_VOL_M_SHORT_ENABLED": True,
                "param_overrides.NORM_VOL_M_SHORT_ALLOW_RTH_PRIME2": True,
                "param_overrides.NORM_VOL_M_SHORT_MIN_VOL_PCT": 50,
                "param_overrides.NORM_VOL_M_SHORT_MAX_VOL_PCT": 80,
                "param_overrides.NORM_VOL_M_SHORT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.NORM_VOL_M_SHORT_MIN_CONTEXT_SCORE": 3,
                "param_overrides.NORM_VOL_M_SHORT_MAX_BREAKOUT_GAP_ATR": 0.50,
                "param_overrides.NORM_VOL_M_SHORT_MAX_STOP_DIST_ATR": 2.20,
            },
        ),
        Experiment(
            "normvol_short_eth_pm_context",
            {
                "param_overrides.NORM_VOL_M_SHORT_ENABLED": True,
                "param_overrides.NORM_VOL_M_SHORT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.NORM_VOL_M_SHORT_MIN_VOL_PCT": 50,
                "param_overrides.NORM_VOL_M_SHORT_MAX_VOL_PCT": 82,
                "param_overrides.NORM_VOL_M_SHORT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.NORM_VOL_M_SHORT_MIN_CONTEXT_SCORE": 4,
                "param_overrides.NORM_VOL_M_SHORT_MAX_BREAKOUT_GAP_ATR": 0.55,
                "param_overrides.NORM_VOL_M_SHORT_MAX_STOP_DIST_ATR": 2.25,
            },
        ),
        Experiment(
            "normvol_short_prime2_pm_balanced",
            {
                "param_overrides.NORM_VOL_M_SHORT_ENABLED": True,
                "param_overrides.NORM_VOL_M_SHORT_ALLOW_RTH_PRIME2": True,
                "param_overrides.NORM_VOL_M_SHORT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.NORM_VOL_M_SHORT_MIN_VOL_PCT": 50,
                "param_overrides.NORM_VOL_M_SHORT_MAX_VOL_PCT": 80,
                "param_overrides.NORM_VOL_M_SHORT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.NORM_VOL_M_SHORT_MIN_CONTEXT_SCORE": 3,
                "param_overrides.NORM_VOL_M_SHORT_MAX_BREAKOUT_GAP_ATR": 0.55,
                "param_overrides.NORM_VOL_M_SHORT_MAX_STOP_DIST_ATR": 2.30,
            },
        ),
        Experiment(
            "normvol_short_prime2_pm_strong",
            {
                "param_overrides.NORM_VOL_M_SHORT_ENABLED": True,
                "param_overrides.NORM_VOL_M_SHORT_ALLOW_RTH_PRIME2": True,
                "param_overrides.NORM_VOL_M_SHORT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.NORM_VOL_M_SHORT_MIN_VOL_PCT": 52,
                "param_overrides.NORM_VOL_M_SHORT_MAX_VOL_PCT": 78,
                "param_overrides.NORM_VOL_M_SHORT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.NORM_VOL_M_SHORT_REQUIRE_STRONG_TREND": True,
                "param_overrides.NORM_VOL_M_SHORT_MIN_CONTEXT_SCORE": 4,
                "param_overrides.NORM_VOL_M_SHORT_MAX_BREAKOUT_GAP_ATR": 0.45,
                "param_overrides.NORM_VOL_M_SHORT_MAX_STOP_DIST_ATR": 2.10,
            },
        ),
    ],
    3: [
        Experiment(
            "highvol_long_prime1_context",
            {
                "param_overrides.HIGH_VOL_M_CONT_ENABLED": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_LONG": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_SHORT": False,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_RTH_PRIME1": True,
                "param_overrides.HIGH_VOL_M_CONT_MIN_VOL_PCT": 80,
                "param_overrides.HIGH_VOL_M_CONT_MAX_VOL_PCT": 95,
                "param_overrides.HIGH_VOL_M_CONT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.HIGH_VOL_M_CONT_MIN_CONTEXT_SCORE_LONG": 3,
                "param_overrides.HIGH_VOL_M_CONT_MIN_TREND_STRENGTH": 0.0,
                "param_overrides.HIGH_VOL_M_CONT_MAX_PULLBACK_ATR": 1.05,
                "param_overrides.HIGH_VOL_M_CONT_MAX_BREAKOUT_GAP_ATR": 0.45,
                "param_overrides.HIGH_VOL_M_CONT_MAX_STOP_DIST_ATR": 2.10,
            },
        ),
        Experiment(
            "highvol_long_prime1_pm_context",
            {
                "param_overrides.HIGH_VOL_M_CONT_ENABLED": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_LONG": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_SHORT": False,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_RTH_PRIME1": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.HIGH_VOL_M_CONT_MIN_VOL_PCT": 80,
                "param_overrides.HIGH_VOL_M_CONT_MAX_VOL_PCT": 95,
                "param_overrides.HIGH_VOL_M_CONT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.HIGH_VOL_M_CONT_MIN_CONTEXT_SCORE_LONG": 4,
                "param_overrides.HIGH_VOL_M_CONT_MIN_TREND_STRENGTH": 0.0,
                "param_overrides.HIGH_VOL_M_CONT_MAX_PULLBACK_ATR": 1.10,
                "param_overrides.HIGH_VOL_M_CONT_MAX_BREAKOUT_GAP_ATR": 0.50,
                "param_overrides.HIGH_VOL_M_CONT_MAX_STOP_DIST_ATR": 2.20,
            },
        ),
        Experiment(
            "highvol_long_dual_context_wide",
            {
                "param_overrides.HIGH_VOL_M_CONT_ENABLED": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_LONG": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_SHORT": False,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_RTH_PRIME1": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.HIGH_VOL_M_CONT_MIN_VOL_PCT": 80,
                "param_overrides.HIGH_VOL_M_CONT_MAX_VOL_PCT": 96,
                "param_overrides.HIGH_VOL_M_CONT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.HIGH_VOL_M_CONT_MIN_CONTEXT_SCORE_LONG": 3,
                "param_overrides.HIGH_VOL_M_CONT_MIN_TREND_STRENGTH": 0.0,
                "param_overrides.HIGH_VOL_M_CONT_MAX_PULLBACK_ATR": 1.15,
                "param_overrides.HIGH_VOL_M_CONT_MAX_BREAKOUT_GAP_ATR": 0.55,
                "param_overrides.HIGH_VOL_M_CONT_MAX_STOP_DIST_ATR": 2.25,
            },
        ),
        Experiment(
            "highvol_long_quality_strict",
            {
                "param_overrides.HIGH_VOL_M_CONT_ENABLED": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_LONG": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_SHORT": False,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_RTH_PRIME1": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.HIGH_VOL_M_CONT_MIN_VOL_PCT": 82,
                "param_overrides.HIGH_VOL_M_CONT_MAX_VOL_PCT": 94,
                "param_overrides.HIGH_VOL_M_CONT_MIN_ALIGNMENT_SCORE": 1,
                "param_overrides.HIGH_VOL_M_CONT_MIN_CONTEXT_SCORE_LONG": 4,
                "param_overrides.HIGH_VOL_M_CONT_REQUIRE_STRONG_TREND": True,
                "param_overrides.HIGH_VOL_M_CONT_MIN_TREND_STRENGTH": 0.25,
                "param_overrides.HIGH_VOL_M_CONT_MAX_PULLBACK_ATR": 0.95,
                "param_overrides.HIGH_VOL_M_CONT_MAX_BREAKOUT_GAP_ATR": 0.40,
                "param_overrides.HIGH_VOL_M_CONT_MAX_STOP_DIST_ATR": 2.00,
            },
        ),
    ],
    4: [
        Experiment(
            "classf_base_context_trim",
            {
                "flags.use_class_F": True,
                "param_overrides.CLASS_F_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_F_MIN_CONTEXT_SCORE": 2,
                "param_overrides.CLASS_F_REQUIRE_STRONG_TREND": True,
            },
        ),
        Experiment(
            "classf_reclaim_pm_context",
            {
                "param_overrides.CLASS_F_RECLAIM_ENABLED": True,
                "param_overrides.CLASS_F_RECLAIM_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.CLASS_F_RECLAIM_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_F_RECLAIM_MIN_CONTEXT_SCORE": 2,
                "param_overrides.CLASS_F_RECLAIM_REQUIRE_STRONG_TREND": False,
                "param_overrides.CLASS_F_RECLAIM_MAX_EXIT_BARS": 10,
                "param_overrides.CLASS_F_RECLAIM_MAX_PULLBACK_ATR": 1.35,
                "param_overrides.CLASS_F_RECLAIM_MAX_STOP_DIST_ATR": 2.10,
            },
        ),
        Experiment(
            "classf_reclaim_prime2_pm_context",
            {
                "param_overrides.CLASS_F_RECLAIM_ENABLED": True,
                "param_overrides.CLASS_F_RECLAIM_ALLOW_RTH_PRIME2": True,
                "param_overrides.CLASS_F_RECLAIM_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.CLASS_F_RECLAIM_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_F_RECLAIM_MIN_CONTEXT_SCORE": 1,
                "param_overrides.CLASS_F_RECLAIM_REQUIRE_STRONG_TREND": False,
                "param_overrides.CLASS_F_RECLAIM_MAX_EXIT_BARS": 10,
                "param_overrides.CLASS_F_RECLAIM_MAX_PULLBACK_ATR": 1.30,
                "param_overrides.CLASS_F_RECLAIM_MAX_STOP_DIST_ATR": 2.10,
            },
        ),
        Experiment(
            "classf_context_reclaim_stack",
            {
                "flags.use_class_F": True,
                "param_overrides.CLASS_F_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_F_MIN_CONTEXT_SCORE": 2,
                "param_overrides.CLASS_F_REQUIRE_STRONG_TREND": True,
                "param_overrides.CLASS_F_RECLAIM_ENABLED": True,
                "param_overrides.CLASS_F_RECLAIM_ALLOW_RTH_PRIME2": True,
                "param_overrides.CLASS_F_RECLAIM_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.CLASS_F_RECLAIM_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_F_RECLAIM_MIN_CONTEXT_SCORE": 2,
                "param_overrides.CLASS_F_RECLAIM_REQUIRE_STRONG_TREND": False,
                "param_overrides.CLASS_F_RECLAIM_MAX_EXIT_BARS": 10,
                "param_overrides.CLASS_F_RECLAIM_MAX_PULLBACK_ATR": 1.25,
            },
        ),
    ],
    5: [
        Experiment(
            "final_context_stack_balanced",
            {
                "param_overrides.CLASS_T_SECONDARY_ENABLED": True,
                "param_overrides.CLASS_T_SECONDARY_ALLOW_RTH_PRIME2": True,
                "param_overrides.CLASS_T_SECONDARY_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.CLASS_T_SECONDARY_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_T_SECONDARY_MIN_CONTEXT_SCORE": 3,
                "param_overrides.CLASS_T_SHORT_ENABLED": True,
                "param_overrides.CLASS_T_SHORT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.CLASS_T_SHORT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_T_SHORT_MIN_CONTEXT_SCORE": 4,
                "param_overrides.NORM_VOL_M_SHORT_ENABLED": True,
                "param_overrides.NORM_VOL_M_SHORT_ALLOW_RTH_PRIME2": True,
                "param_overrides.NORM_VOL_M_SHORT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.NORM_VOL_M_SHORT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.NORM_VOL_M_SHORT_MIN_CONTEXT_SCORE": 3,
                "param_overrides.HIGH_VOL_M_CONT_ENABLED": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_LONG": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_SHORT": False,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_RTH_PRIME1": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.HIGH_VOL_M_CONT_MIN_VOL_PCT": 80,
                "param_overrides.HIGH_VOL_M_CONT_MAX_VOL_PCT": 95,
                "param_overrides.HIGH_VOL_M_CONT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.HIGH_VOL_M_CONT_MIN_CONTEXT_SCORE_LONG": 3,
            },
        ),
        Experiment(
            "final_context_stack_pm_focus",
            {
                "param_overrides.CLASS_T_SECONDARY_ENABLED": True,
                "param_overrides.CLASS_T_SECONDARY_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.CLASS_T_SECONDARY_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_T_SECONDARY_MIN_CONTEXT_SCORE": 4,
                "param_overrides.CLASS_T_SHORT_ENABLED": True,
                "param_overrides.CLASS_T_SHORT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.CLASS_T_SHORT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_T_SHORT_MIN_CONTEXT_SCORE": 4,
                "param_overrides.NORM_VOL_M_SHORT_ENABLED": True,
                "param_overrides.NORM_VOL_M_SHORT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.NORM_VOL_M_SHORT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.NORM_VOL_M_SHORT_MIN_CONTEXT_SCORE": 4,
                "param_overrides.HIGH_VOL_M_CONT_ENABLED": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_LONG": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_SHORT": False,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.HIGH_VOL_M_CONT_MIN_VOL_PCT": 80,
                "param_overrides.HIGH_VOL_M_CONT_MAX_VOL_PCT": 95,
                "param_overrides.HIGH_VOL_M_CONT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.HIGH_VOL_M_CONT_MIN_CONTEXT_SCORE_LONG": 4,
            },
        ),
        Experiment(
            "final_context_stack_quality",
            {
                "param_overrides.CLASS_T_SECONDARY_ENABLED": True,
                "param_overrides.CLASS_T_SECONDARY_ALLOW_RTH_PRIME2": True,
                "param_overrides.CLASS_T_SECONDARY_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.CLASS_T_SECONDARY_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_T_SECONDARY_MIN_CONTEXT_SCORE": 4,
                "param_overrides.CLASS_T_SHORT_ENABLED": True,
                "param_overrides.CLASS_T_SHORT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.CLASS_T_SHORT_ALLOW_RTH_PRIME2": True,
                "param_overrides.CLASS_T_SHORT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_T_SHORT_MIN_CONTEXT_SCORE": 4,
                "param_overrides.NORM_VOL_M_SHORT_ENABLED": True,
                "param_overrides.NORM_VOL_M_SHORT_ALLOW_RTH_PRIME2": True,
                "param_overrides.NORM_VOL_M_SHORT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.NORM_VOL_M_SHORT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.NORM_VOL_M_SHORT_REQUIRE_STRONG_TREND": True,
                "param_overrides.NORM_VOL_M_SHORT_MIN_CONTEXT_SCORE": 4,
                "param_overrides.HIGH_VOL_M_CONT_ENABLED": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_LONG": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_SHORT": False,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_RTH_PRIME1": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.HIGH_VOL_M_CONT_MIN_VOL_PCT": 82,
                "param_overrides.HIGH_VOL_M_CONT_MAX_VOL_PCT": 94,
                "param_overrides.HIGH_VOL_M_CONT_MIN_ALIGNMENT_SCORE": 1,
                "param_overrides.HIGH_VOL_M_CONT_MIN_CONTEXT_SCORE_LONG": 4,
                "param_overrides.HIGH_VOL_M_CONT_REQUIRE_STRONG_TREND": True,
            },
        ),
        Experiment(
            "final_context_stack_reclaim",
            {
                "param_overrides.CLASS_T_SECONDARY_ENABLED": True,
                "param_overrides.CLASS_T_SECONDARY_ALLOW_RTH_PRIME2": True,
                "param_overrides.CLASS_T_SECONDARY_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.CLASS_T_SECONDARY_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_T_SECONDARY_MIN_CONTEXT_SCORE": 3,
                "param_overrides.NORM_VOL_M_SHORT_ENABLED": True,
                "param_overrides.NORM_VOL_M_SHORT_ALLOW_RTH_PRIME2": True,
                "param_overrides.NORM_VOL_M_SHORT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.NORM_VOL_M_SHORT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.NORM_VOL_M_SHORT_MIN_CONTEXT_SCORE": 3,
                "param_overrides.HIGH_VOL_M_CONT_ENABLED": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_LONG": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_SHORT": False,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_RTH_PRIME1": True,
                "param_overrides.HIGH_VOL_M_CONT_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.HIGH_VOL_M_CONT_MIN_VOL_PCT": 80,
                "param_overrides.HIGH_VOL_M_CONT_MAX_VOL_PCT": 95,
                "param_overrides.HIGH_VOL_M_CONT_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.HIGH_VOL_M_CONT_MIN_CONTEXT_SCORE_LONG": 3,
                "param_overrides.CLASS_F_RECLAIM_ENABLED": True,
                "param_overrides.CLASS_F_RECLAIM_ALLOW_RTH_PRIME2": True,
                "param_overrides.CLASS_F_RECLAIM_ALLOW_ETH_QUALITY_PM": True,
                "param_overrides.CLASS_F_RECLAIM_MIN_ALIGNMENT_SCORE": 0,
                "param_overrides.CLASS_F_RECLAIM_MIN_CONTEXT_SCORE": 2,
                "param_overrides.CLASS_F_RECLAIM_REQUIRE_STRONG_TREND": False,
            },
        ),
    ],
}


def get_phase_candidates(
    phase: int,
    suggested_experiments: list[tuple[str, dict]] | None = None,
) -> list[tuple[str, dict]]:
    candidates = [
        (experiment.name, dict(experiment.mutations))
        for experiment in _TARGETED_PHASE_CANDIDATES.get(phase, [])
    ]

    if suggested_experiments:
        existing = {name for name, _ in candidates}
        for name, mutations in suggested_experiments:
            if name not in existing:
                candidates.append((name, dict(mutations)))
                existing.add(name)
    return candidates
